name: healthpilot
description: A smart calorie and nutrition tracking app.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  http: ^1.2.2
  uuid: ^4.5.1
  intl: ^0.19.0
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/healthpilot_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/healthpilot_logo.png
